import * as fs from "node:fs";
import * as path from "node:path";

const OUTPUT_FILE = ".env.mongobridge";

const TEMPLATE = `# Generated by mongobridge generate:env
# Fill the values below. Keep this file out of version control.

# Required
MONGOBRIDGE_DB=

# Core profiles
MONGO_LOCAL_URI=
MONGO_ATLAS_URI=

# Optional aliases / extra profiles
MONGO_REMOTE_URI=
MONGO_STAGING_DB_URL=
MONGO_PRODUCTION_DB_URL=
`;

export async function cmdGenerateEnv(): Promise<void> {
  const outPath = path.join(process.cwd(), OUTPUT_FILE);
  if (fs.existsSync(outPath)) {
    throw new Error(
      `${OUTPUT_FILE} already exists in this folder. Remove it first if you want to regenerate it.`,
    );
  }

  fs.writeFileSync(outPath, TEMPLATE, { encoding: "utf8" });
  console.log(`Created ${OUTPUT_FILE} in ${process.cwd()}`);
}
